[package]
name = "thisko"
version = "0.1.0"
edition = "2021"
authors = ["pySatellite <pysatellite@gmail.com>"]
rust-version = "1.73"
description = "Python ğŸ and Rust ğŸ¦€ Intercalling ğŸ¤"
readme = "README.md"
repository = "https://github.com/pySatellite/thisko"
license = "Apache-2.0"
keywords = ["python", "edu"]
publish = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
